### ISSUE TITLE
[Bug] 일시 정지 시 플레이어 키입력 버그

### ISSUE THREAD

**Issue by SeungJu0406** [SeungJu0406/SpiritSavior#110]
# 1. 버그 개요
- 일시정지 하였을때 플레이어 키입력에 대해 원하지 않는 현상 발생

# 2. 상황 재현
- 일시정지, timeScale을 0으로 바꿈
- 플레이어 키입력은 되는 상태, 키입력을 통해 상태를 바꿀 수 있음
- 이 상태에서 스페이스바를 연타하여 공중으로 높이 올라갈 수 있음

# 3. 예상 원인
- timeScale이 0인 상황에서 플레이어 입력이 되다보니 발생하는 문제

# 4. 참고자료
![Honeycam 2024-10-29 11-47-56](https://github.com/user-attachments/assets/f98b25be-01c6-4903-b537-ddcd3f3a36e4)

# 5. 구동 환경
- Window / Unity Editor 2021.3.42f1

# 6. 추가 코멘트

**Comment by EUSUNGKIM** [comment]
일시정지시 움직이는 버그 해결했습니다~
