### ISSUE TITLE
[Bug] 캐릭터 spawn state 스택 오버플로

### ISSUE THREAD

**Issue by SeungJu0406** [SeungJu0406/SpiritSavior#125]
# 1. 버그 개요
- 캐릭터 부활 상태에서 스택 오버플로 문제 발생

# 2. 상황 재현
1. 캐릭터 죽음
2. 부활했을때 계속 스폰 Enter가 호출됨

# 3. 예상 원인
- Enter에서 또 spawn상태로 전환중임

# 4. 참고자료
![화면 캡처 2024-10-29 151933](https://github.com/user-attachments/assets/4676d034-15bc-4376-9934-f43ebfdf4d5f)

# 5. 구동 환경
- Window / Unity Editor 2021.3.42f1

# 6. 추가 코멘트

![화면 캡처 2024-10-29 152612](https://github.com/user-attachments/assets/d83eedca-9a30-4255-a3f9-2125da8a6da4)

- 이 부분이 문제

**Comment by SeungJu0406** [comment]
잠깐 주석처리 하겠습니다. 확인하시고 해당부분을 삭제하실지, 적절하게 수정하실지 피드백 바랍니다

**Comment by LemoZun** [comment]
스폰 상태로 전환하는 과정을 변경해 수정 완료했습니다
