### ISSUE TITLE
[Bug] Warp UI Button Object의 Update 비활성화 문제

### ISSUE THREAD

**Issue by KanghyeokYeo** [SeungJu0406/SpiritSavior#132]
# 1. 버그 개요
- Warp UI Button Object를 상황에 맞게 활성화/비활성화 구현 중 Update함수가 작동되지 않는 문제 발생

# 2. 상황 재현
1. Warp Point Controller를 통해 한번 지나간 warp point를 활성화하고자 warp Acrive 활성화/비활성화 구현
2. Warp Point Controller를 통해 warp UI를 켜고 끄도록 구현
3. Warp Button Controller를 통해 warp UI를 켰을 경우 warp Active 활성화 된 warp point로 향하는 button만 활성화(setActive)하기 위해 update함수에 작성
4. 게임을 실행시켰을 때 해당 update함수가 작동하지 않는 버그가 발생함

# 3. 예상 원인
- button에 해당 script가 적절히 반영되지 않은 문제로 추측

# 4. 참고자료
![image](https://github.com/user-attachments/assets/a36b1114-54f4-4be5-8308-d17116ef58be)
![image](https://github.com/user-attachments/assets/f38995fc-6e77-46a8-a373-188fb0028bdd)
start 함수가 작동되는 것은 확인되었으나, update 함수가 작동하지 않음을 확인할 수 있음

**Comment by KanghyeokYeo** [comment]
update 대신 coroutine으로 대체해보려 했으나 아직까지 성공하지 못한 상황

**Comment by SeungJu0406** [comment]
![화면 캡처 2024-10-29 220058](https://github.com/user-attachments/assets/504eb7c2-365a-4969-b0ef-f1f4305da964)

이 방법은 어떨까요?

**Comment by KanghyeokYeo** [comment]
IEnumerator 활용하여 update함수를 대체함
