### ISSUE TITLE
[Bug] 움직이는 발판 버그

### ISSUE THREAD

**Issue by SeungJu0406** [SeungJu0406/SpiritSavior#146]
# 1. 버그 개요
- 움직이는 발판에 대한 여러가지 버그 발견

# 2. 상황 재현
1. 플레이어가 발판에 탑승하지 않고 옆에 부딪혔는데도 탑승한것으로 판정되어 발판에 따라가짐
2. 플레이어가 탑승한 상태로 움직이면 계속 발판의 상태가 바뀜

# 3. 예상 원인
- 플레이어 자식 상속 방식에 대한 문제?
- 다른 방법에 대해

# 4. 참고자료
![Honeycam 2024-10-30 15-18-58](https://github.com/user-attachments/assets/67dbefd7-5ad0-4cab-80b5-d3ccb091eb41)
![Honeycam 2024-10-30 15-19-18](https://github.com/user-attachments/assets/a363afc4-ae03-4e58-ae71-231bbd0c20cc)

# 5. 구동 환경
- Window / Unity Editor 2021.3.42f1

# 6. 추가 코멘트
```

    /// <summary>
    /// 플레이어 움직이는 메서드
    /// </summary>
    public void MovePlatform()
    {
        Debug.Log("start moving");
        transform.position = Vector3.MoveTowards(transform.position, nextPosition, moveSpeed * Time.deltaTime);
    }
```
- 해당 코드에서 nextPosition 으로 이동보다는 pointB.position이 괜찮을 것 같습니다

**Comment by YoungsonMan** [comment]
위에 혹시 그 잔디 발판이 collider가 안평평한건가요? 그냥 평평한 네모위에서는 괜찮은같아서

근데 닿으면 가는거는 확실히 밟으면 되는걸로 뭔가 조치해야겠네요

**Comment by SeungJu0406** [comment]
평평한 발판에서는 확실히 잘되네요
그렇다면 발판 감지 트리거 혹은 콜라이더만 따로 발판 위쪽에 그리고 옆면 콜라이더보다 작게해서 배치하는 것은 어떨까요?

**Comment by SeungJu0406** [comment]
![화면 캡처 2024-10-30 154447](https://github.com/user-attachments/assets/dce4dd5c-da16-43d1-b3bc-01e2ebb305da)

발판감지 트리거를 따로 배치해서 적용 해봤습니다

**Comment by YoungsonMan** [comment]
위에 방법으로 해결
