### ISSUE TITLE
[Bug] 캐릭터 트리거 통과 불가 버그

### ISSUE THREAD

**Issue by SeungJu0406** [SeungJu0406/SpiritSavior#186]
# 1. 버그 개요
- 캐릭터 트리거 통과 불가 버그

# 2. 상황 재현
1. 캐릭터 트리거 통과 시도
2. Run 상태에서 트리거를 통과하지 못함
3. Jump 상태로 들어갔을때는 트리거 통과 가능
4. 만약 트리거의 레이어가 Wall 이었다면 벽타기도 가능함

# 3. 예상 원인
- 레이캐스트로 벽감지를 행하는 로직에 대해 무슨 문제가 생긴듯

# 4. 참고자료
![Honeycam 2024-11-01 01-28-26](https://github.com/user-attachments/assets/ae5c7421-ed1f-4b13-8671-7cfd41f3bb63)

# 5. 구동 환경
- Window / Unity Editor 2021.3.42f1

# 6. 추가 코멘트

**Comment by LemoZun** [comment]
해결했습니다
