### ISSUE TITLE
[Bug] 플레이어 경사면 관련 버그

### ISSUE THREAD

**Issue by SeungJu0406** [SeungJu0406/SpiritSavior#217]
# 1. 버그 개요
- 플레이어 경사면 관련 버그

# 2. 상황 재현
- 속성발판 통과(다른 색상일 때)
- 통과하지 못함
- Max Angle 값을 변경해주면 통과함

# 3. 예상 원인
-  경사면에서 Ignore Player 레이어또한 감지하기 때문에 이동을 막아버린듯?

# 4. 참고자료
![Honeycam 2024-11-03 00-23-27](https://github.com/user-attachments/assets/1972e051-d753-49fb-a385-1be3b57b9a8d)

# 5. 구동 환경
- Window / Unity Editor 2021.3.42f1

# 6. 추가 코멘트

**Comment by LemoZun** [comment]
if ((_ignorePlayerLayerMask & (1 << wallHit.collider.gameObject.layer)) != 0)
       {
           return;
       }
       해결했습니다
