### ISSUE TITLE
[Bug] GrassParticle 버그

### ISSUE THREAD

**Issue by SeungJu0406** [SeungJu0406/SpiritSavior#228]
# 1. 버그 개요
- GrassParticle 버그

# 2. 상황 재현
- 땅밟으니까 버그남
- GrassParticle , 잔디쪽밟으니까 버그나는듯

# 3. 예상 원인

# 4. 참고자료
![화면 캡처 2024-11-04 104336](https://github.com/user-attachments/assets/68a90b4f-5c6f-4cb7-97b5-d8f87379cafa)

![화면 캡처 2024-11-04 104357](https://github.com/user-attachments/assets/8b6366d9-dbfe-42f5-8fd4-3aaf739489e8)

# 5. 구동 환경

- Window / Unity Editor 2021.3.42f1

# 6. 추가 코멘트

**Comment by YoungsonMan** [comment]
파티클 매니저랑 연결해 두고
파티클 매니저 Public > Prefabs > Manager 에 넣었습니다.
![2024-11-04_GrassEffectHowToPM01](https://github.com/user-attachments/assets/72019f59-e4b9-4701-965c-cda4d87a3cad)
파티클 매니저 하이어아키 창에 배치하면 됩니다
![2024-11-04_GrassEffectHowToPM02](https://github.com/user-attachments/assets/7ca119ea-2ceb-4c5f-b6e6-09595a38300d)
