### ISSUE TITLE
[Bug] 랜딩 상태 및 idle 상태 버그

### ISSUE THREAD

**Issue by SeungJu0406** [SeungJu0406/SpiritSavior#235]
# 1. 버그 개요
- 랜딩 상태 및 idle 상태 버그

# 2. 상황 재현
- 버섯 발판 밟았을 때 버그 
- 끝까지 올라가지 못하고 바로 떨어짐

# 3. 예상 원인
- 랜딩State -> Idle상태에서 물리값 0 초기화 -> 바로 떨어지면서 fall 상태 전환

# 4. 참고자료
![Honeycam 2024-11-04 11-44-17](https://github.com/user-attachments/assets/7591c85e-e2d2-4291-a963-e921ecce02bd)

# 5. 구동 환경
- Window / Unity Editor 2021.3.42f1

# 6. 추가 코멘트

**Comment by LemoZun** [comment]
버섯 콜라이더 수정 및 idle 상태 진입시 속도 벡터 제로 현상 수정으로 완료했습니다
