### ISSUE TITLE
[Bug] 가시 함정과 충돌했을 때 뒤로 밀려나기

### ISSUE THREAD

**Issue by KanghyeokYeo** [SeungJu0406/SpiritSavior#51]
# 1. 버그 개요
- 가시 함정과 충돌 시 x축으로 안 밀리는 경우 발생

# 2. 상황 재현
- 가시함정과 충돌한 플레이어를 밀어내기 위해 AddForce() 함수를 이용하여 코드 작성
![image](https://github.com/user-attachments/assets/ef22f2df-fc08-47f6-8e68-cca7683c79d3)

- 가시함정 상단부분에서 충돌할 경우 밀려나는 현상이 뚜렷하게 나타나고, 하단에서 밀러나지 않음

# 3. 예상 원인
- 충돌 이후 플레이어가 이동하면서 밀려나던 과정이 즉시 사라짐으로 추측

# 4. 참고자료
- 이미지, 동영상 캡쳐본 등 참고자료가 있을 경우 링크 기재

# 6. 추가 코멘트
- 해당 스크립트를 가시 함정이 아닌 플레이어 스크립트로 작성하고 싶었으나, 충돌 판정의 경우 가시함정과 다른 오브젝트를 구별하는 과정도 필요할 듯 함

**Comment by KanghyeokYeo** [comment]
추후에 가시함정에 대한 tag가 정의될 수 있는지 확인하고 스크립트를 플레이어 적용으로 변경하고자 함

**Comment by SeungJu0406** [comment]
gap 변수를 통해 왼쪽으로 밀려날지 오른쪽으로 밀려날지 결정하는것에 대해서는 좋은 접근이라고 생각합니다.
다만 해당 방식으로만 사용하면 캐릭터가 해당 오브젝트와 부딪힌 위치에 따라 밀려나는 힘값도 달라지게 되니 해당 gap이 0보다 클때는 1, 0보다 작을때는 -1로 처리하는 것이 어떨까 합니다
추가로 가시오브젝트에 대해 콜라이더 충돌처리보다는 트리거 충돌처리를 더 추천드립니다

**Comment by SeungJu0406** [comment]
해당 버그에 대해서는 플레이어에 HitState 를 적용하여 해당 상태에 따른 잠깐의 시간동안 이동을 막는 로직을 구현하면 해결될듯 합니다.
현재 캐릭터 이동을 담당하고 계시는 준민님과의 상의를 통해 해당 스크립트를 Hit State의 로직으로 적용시키는것이 괜찮다고 생각합니다. 그리고 가시 오브젝트에 대해서 플레이어에게 데미지를 입히는 플레이어컨트롤러 클래스의 TakeDamage 메서드를 통해 접근하시는 것을 추천합니다

**Comment by KanghyeokYeo** [comment]
준민님과 상의를 통해 플레이어의 HitState를 적용하기 위해 PlayerController 클래스를 불러와서 충돌(피격) 시 데미지를 받도록 함과 동시에 체력이 깎이도록 완성하였습니다.

**Comment by SeungJu0406** [comment]
네 확인했습니다
